FROM python:3.11

WORKDIR /app

COPY requirements-api.txt .
RUN pip install -r requirements-api.txt

COPY data/ ./data/
COPY src/ ./src/

CMD ["uvicorn", "src.api:app", "--host", "0.0.0.0", "--port", "8000"]